export const PRODUCTS_LOAD = 'PRODUCTS_LOAD'
export const PRODUCTS_SUCCESS  = 'PRODUCTS_SUCCESS'
export const PRODUCTS_FAILURE  = 'PRODUCTS_FAILURE'

export const PRODUCT_LOAD = 'PRODUCT_LOAD'
export const PRODUCT_SUCCESS  = 'PRODUCT_SUCCESS'
export const PRODUCT_FAILURE  = 'PRODUCT_FAILURE'

export const LOGIN_LOAD = 'LOGIN_LOAD'
export const LOGIN_SUCCESS  = 'PRODUCT_SUCCESS'
export const LOGIN_FAILURE  = 'LOGIN_FAILURE'